### ISSUE TITLE
Can it work with pickle.dump/json.dump instead of text only ?

### ISSUE THREAD

**Issue by sionking** [untitaker/python-atomicwrites#29]
I want to make my dumps atomic.

SCK.

**Comment by untitaker** [comment]
Use `dumps` instead of `dump` and write its return value to the file. Please use StackOverflow or the [python irc channel](https://www.python.org/community/irc/) for help on this.

**Comment by sionking** [comment]
This does not work.

    from atomicwrites import atomic_write
    import pickle

    dict1 = {'goo':1,'mos':2}
    with atomic_write('foo.txt', overwrite=True) as f:
        f.write(pickle.dumps(dict1))
TypeError: must be str, not bytes

**Comment by sionking** [comment]
https://stackoverflow.com/questions/50461868/trying-to-use-atomic-write-on-pickle-object

**Comment by untitaker** [comment]
Hey, I just fished this out of my email backlog and I'm sorry I didn't respond to your StackOverflow post back then. I can't remember why I recommended to use `dumps` here instead of `dump`, either should've worked fine.

As you correctly noted you need the `b` flag to write binary data such as pickled objects
